import 'package:flutter/material.dart';

// Localization strings
class AppStrings {
  static const Map<String, Map<String, String>> localizedStrings = {
    'en': {
      'settings': 'Settings',
      'managePreferences': 'Manage your app preferences',
      'notifications': 'Notifications',
      'pushNotifications': 'Push Notifications',
      'receiveNotifications': 'Receive app notifications',
      'emailUpdates': 'Email Updates',
      'receiveEmailUpdates': 'Receive updates via email',
      'appearance': 'Appearance',
      'darkMode': 'Dark Mode',
      'enableDarkTheme': 'Enable dark theme',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'support': 'Support',
      'helpCenter': 'Help Center',
      'getHelp': 'Get help and support',
      'about': 'About',
      'appVersion': 'App version and information',
      'rateApp': 'Rate App',
      'shareFeeling': 'Share your feedback',
      'legal': 'Legal',
      'privacyPolicy': 'Privacy Policy',
      'viewPrivacy': 'View our privacy policy',
      'termsOfService': 'Terms of Service',
      'viewTerms': 'View terms and conditions',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'profile': 'Profile',
      'home': 'Home',
      'search': 'Search',
      'orders': 'Orders',
      'welcome': 'Welcome',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'fullName': 'Full Name',
      'phoneNumber': 'Phone Number',
      'confirmPassword': 'Confirm Password',
      'forgotPassword': 'Forgot Password?',
      'signUp': 'Sign Up',
      'signIn': 'Sign In',
      'noAccount': 'Don\'t have an account?',
      'haveAccount': 'Already have an account?',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'message': 'Message',
    },
    'es': {
      'settings': 'Configuración',
      'managePreferences': 'Administre sus preferencias de aplicación',
      'notifications': 'Notificaciones',
      'pushNotifications': 'Notificaciones push',
      'receiveNotifications': 'Recibir notificaciones de aplicaciones',
      'emailUpdates': 'Actualizaciones por correo electrónico',
      'receiveEmailUpdates': 'Recibir actualizaciones por correo electrónico',
      'appearance': 'Apariencia',
      'darkMode': 'Modo oscuro',
      'enableDarkTheme': 'Activar tema oscuro',
      'language': 'Idioma',
      'selectLanguage': 'Seleccionar idioma',
      'support': 'Soporte',
      'helpCenter': 'Centro de ayuda',
      'getHelp': 'Obtener ayuda y soporte',
      'about': 'Acerca de',
      'appVersion': 'Información y versión de la aplicación',
      'rateApp': 'Calificar aplicación',
      'shareFeeling': 'Comparta sus comentarios',
      'legal': 'Legal',
      'privacyPolicy': 'Política de privacidad',
      'viewPrivacy': 'Ver nuestra política de privacidad',
      'termsOfService': 'Términos de servicio',
      'viewTerms': 'Ver términos y condiciones',
      'logout': 'Cerrar sesión',
      'cancel': 'Cancelar',
      'profile': 'Perfil',
      'home': 'Inicio',
      'search': 'Buscar',
      'orders': 'Pedidos',
      'welcome': 'Bienvenido',
      'login': 'Iniciar sesión',
      'register': 'Registrarse',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'fullName': 'Nombre completo',
      'phoneNumber': 'Número de teléfono',
      'confirmPassword': 'Confirmar contraseña',
      'forgotPassword': '¿Olvidó su contraseña?',
      'signUp': 'Registrarse',
      'signIn': 'Iniciar sesión',
      'noAccount': '¿No tienes una cuenta?',
      'haveAccount': '¿Ya tienes una cuenta?',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'message': 'Mensaje',
    },
    'fr': {
      'settings': 'Paramètres',
      'managePreferences': 'Gérez vos préférences d\'application',
      'notifications': 'Notifications',
      'pushNotifications': 'Notifications push',
      'receiveNotifications': 'Recevoir les notifications de l\'application',
      'emailUpdates': 'Mises à jour par e-mail',
      'receiveEmailUpdates': 'Recevoir les mises à jour par e-mail',
      'appearance': 'Apparence',
      'darkMode': 'Mode sombre',
      'enableDarkTheme': 'Activer le thème sombre',
      'language': 'Langue',
      'selectLanguage': 'Sélectionner la langue',
      'support': 'Support',
      'helpCenter': 'Centre d\'aide',
      'getHelp': 'Obtenir de l\'aide et du support',
      'about': 'À propos',
      'appVersion': 'Informations et version de l\'application',
      'rateApp': 'Évaluer l\'application',
      'shareFeeling': 'Partagez vos commentaires',
      'legal': 'Juridique',
      'privacyPolicy': 'Politique de confidentialité',
      'viewPrivacy': 'Voir notre politique de confidentialité',
      'termsOfService': 'Conditions d\'utilisation',
      'viewTerms': 'Voir les termes et conditions',
      'logout': 'Déconnexion',
      'cancel': 'Annuler',
      'profile': 'Profil',
      'home': 'Accueil',
      'search': 'Recherche',
      'orders': 'Commandes',
      'welcome': 'Bienvenue',
      'login': 'Connexion',
      'register': 'S\'inscrire',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'fullName': 'Nom complet',
      'phoneNumber': 'Numéro de téléphone',
      'confirmPassword': 'Confirmer le mot de passe',
      'forgotPassword': 'Mot de passe oublié?',
      'signUp': 'S\'inscrire',
      'signIn': 'Se connecter',
      'noAccount': 'Vous n\'avez pas de compte?',
      'haveAccount': 'Vous avez déjà un compte?',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'message': 'Message',
    },
    'de': {
      'settings': 'Einstellungen',
      'managePreferences': 'Verwalten Sie Ihre App-Einstellungen',
      'notifications': 'Benachrichtigungen',
      'pushNotifications': 'Push-Benachrichtigungen',
      'receiveNotifications': 'App-Benachrichtigungen erhalten',
      'emailUpdates': 'E-Mail-Updates',
      'receiveEmailUpdates': 'E-Mail-Updates erhalten',
      'appearance': 'Erscheinungsbild',
      'darkMode': 'Dunkler Modus',
      'enableDarkTheme': 'Dunkles Design aktivieren',
      'language': 'Sprache',
      'selectLanguage': 'Sprache auswählen',
      'support': 'Unterstützung',
      'helpCenter': 'Hilfecenter',
      'getHelp': 'Hilfe und Support erhalten',
      'about': 'Über',
      'appVersion': 'App-Version und Informationen',
      'rateApp': 'App bewerten',
      'shareFeeling': 'Teilen Sie Ihr Feedback',
      'legal': 'Rechtliche',
      'privacyPolicy': 'Datenschutzrichtlinie',
      'viewPrivacy': 'Unsere Datenschutzrichtlinie anzeigen',
      'termsOfService': 'Nutzungsbedingungen',
      'viewTerms': 'Allgemeine Geschäftsbedingungen anzeigen',
      'logout': 'Abmelden',
      'cancel': 'Abbrechen',
      'profile': 'Profil',
      'home': 'Startseite',
      'search': 'Suche',
      'orders': 'Bestellungen',
      'welcome': 'Willkommen',
      'login': 'Anmelden',
      'register': 'Registrieren',
      'email': 'E-Mail',
      'password': 'Passwort',
      'fullName': 'Vollständiger Name',
      'phoneNumber': 'Telefonnummer',
      'confirmPassword': 'Passwort bestätigen',
      'forgotPassword': 'Passwort vergessen?',
      'signUp': 'Registrieren',
      'signIn': 'Anmelden',
      'noAccount': 'Haben Sie kein Konto?',
      'haveAccount': 'Haben Sie bereits ein Konto?',
      'loading': 'Wird geladen...',
      'error': 'Fehler',
      'success': 'Erfolg',
      'message': 'Nachricht',
    },
    'ne': {
      'settings': 'सेटिङ्स',
      'managePreferences': 'आपको अनुप्रयोग वरीयताहरू प्रबन्ध गर्नुहोस्',
      'notifications': 'सूचनाहरू',
      'pushNotifications': 'पुश सूचनाहरू',
      'receiveNotifications': 'अनुप्रयोग सूचनाहरू प्राप्त गर्नुहोस्',
      'emailUpdates': 'इमेल अपडेटहरू',
      'receiveEmailUpdates': 'इमेल अपडेटहरू प्राप्त गर्नुहोस्',
      'appearance': 'उपस्थिति',
      'darkMode': 'अँध्यारो मोड',
      'enableDarkTheme': 'अँध्यारो थिम सक्षम गर्नुहोस्',
      'language': 'भाषा',
      'selectLanguage': 'भाषा चयन गर्नुहोस्',
      'support': 'समर्थन',
      'helpCenter': 'सहायता केन्द्र',
      'getHelp': 'सहायता र समर्थन प्राप्त गर्नुहोस्',
      'about': 'बारेमा',
      'appVersion': 'अनुप्रयोग संस्करण र जानकारी',
      'rateApp': 'अनुप्रयोग मूल्याङ्कन गर्नुहोस्',
      'shareFeeling': 'आपको प्रतिक्रिया साझा गर्नुहोस्',
      'legal': 'कानूनी',
      'privacyPolicy': 'गोपनीयता नीति',
      'viewPrivacy': 'हाम्रो गोपनीयता नीति हेर्नुहोस्',
      'termsOfService': 'सेवा शर्तहरू',
      'viewTerms': 'शर्तहरू र शर्तहरू हेर्नुहोस्',
      'logout': 'लग आउट गर्नुहोस्',
      'cancel': 'रद्द गर्नुहोस्',
      'profile': 'प्रोफाइल',
      'home': 'गृह',
      'search': 'खोज',
      'orders': 'आदेशहरू',
      'welcome': 'स्वागतम',
      'login': 'लगइन गर्नुहोस्',
      'register': 'दर्ता गर्नुहोस्',
      'email': 'इमेल',
      'password': 'पासवर्ड',
      'fullName': 'पूरा नाम',
      'phoneNumber': 'फोन नम्बर',
      'confirmPassword': 'पासवर्ड पुष्टि गर्नुहोस्',
      'forgotPassword': 'पासवर्ड भुल्नुभयो?',
      'signUp': 'दर्ता गर्नुहोस्',
      'signIn': 'साइन इन गर्नुहोस्',
      'noAccount': 'खाता छैन?',
      'haveAccount': 'पहिले नै खाता छ?',
      'loading': 'लोड हुँदै...',
      'error': 'त्रुटि',
      'success': 'सफलता',
      'message': 'संदेश',
    },
  };

  static String get(String key, {String languageCode = 'en'}) {
    return localizedStrings[languageCode]?[key] ?? localizedStrings['en']?[key] ?? key;
  }

  static String translate(BuildContext context, String key) {
    // This would be used if you have access to BuildContext
    // For now, this is a placeholder for future implementation
    return key;
  }
}

// Extension for easy access
extension StringLocalization on BuildContext {
  String translate(String key) {
    return AppStrings.get(key);
  }
}
